packages:
  - 'teraverse-v2'
  - 'gigaverse-sdk'
  - 'gigaverse-engine'
allowBuilds:
  '@reown/appkit': true
  bufferutil: true
  keccak: true
  secp256k1: true
  sharp: true
  unrs-resolver: true
  utf-8-validate: true
